# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Publish

#on:
#  push:
#    branches: [ master ]

env:
  ROOT_DOC_DIR: doc/global
  C_DOC_DIR: c_common/doc/html
  PY_DOC_DIR: doc/source/_build/html
  DEPLOY_DIR: deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout SupportScripts
        uses: actions/checkout@v2
        with:
          repository: SpiNNakerManchester/SupportScripts
          path: support
      - name: Checkout SpiNNaker C Dependencies
        run: |
          support/gitclone2.sh https://github.com/SpiNNakerManchester/spinnaker_tools.git
      - name: Set dynamic environment variables
        # This step can not be merged with Checkout Spinnaker Dependencies
        run: |
          echo "Set SPINN_DIRS to $PWD/spinnaker_tools"
          echo "SPINN_DIRS=$PWD/spinnaker_tools" >> $GITHUB_ENV
          echo "GITHUB_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Read tags
        run: make doxysetup
        working-directory: c_common

      - name: Build Python Documentation
        run: sphinx-build -W -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
        working-directory: doc/source

      - name: Build C documentation
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: c_common

      - name: Merge documentation trees
        run: |
          cp -vaT $ROOT_DOC_DIR $DEPLOY_DIR
          cp -vaT $C_DOC_DIR $DEPLOY_DIR/c
          cp -vaT $PY_DOC_DIR $DEPLOY_DIR/python

      - name: TEST THE DOC TREE
        run: ls -lAR
        working-directory: ${{ env.DEPLOY_DIR }}

#      - name: Deploy to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@3.7.1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: gh-pages
#          folder: ${{ env.DEPLOY_DIR }}
